version: '3.8'
services:
  plex:
    image: ghcr.io/linuxserver/plex:amd64-latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/kinsun/config:/config
      - /home/kinsun/media:/movies/media
      - /home/kinsun/Torrent:/movies/Torrent
    restart: always
  transmission:
    image: ghcr.io/linuxserver/transmission:amd64-latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - USER=kinsun
      - PASS=pandora
    volumes:
      - /home/kinsun/config:/config
      - /home/kinsun/Torrent:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=pandora
      - POSTGRES_DB=anime
    ports:
      - 5433:5432
    restart: always
  anime-download:
    image: anime-download:latest
    network_mode: host
    container_name: anime-download
    depends_on:
      - postgres
    restart: always
