name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker
      run: docker login -u $DOCKER_USER -p $DOCKER_PW
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anime-download:latest
    - name: Push Image
      run: docker push lsping8/anime-download:latest
